library(dplyr)
library(grDevices)
setwd('D:/Data Science/4. Exploratory Data Analysis/Project 1')
house_pwr_cons <- read.table(file = "hpc.txt", header = TRUE, sep = ';', na.strings = '?')
hpc_TFS <- filter(house_pwr_cons, as.Date(Date, format="%d/%m/%Y") == '2007-02-01' | as.Date(Date, format="%d/%m/%Y") == '2007-02-02')
hpc_TFS$Date <- strptime(paste(hpc_TFS$Date, hpc_TFS$Time), "%d/%m/%Y %H:%M:%S")
png(file = "plot2.png", height = 480, width = 480, units = "px")
with(hpc_TFS, plot(Date, Global_active_power, type='l', xlab = '', ylab = 'Global Active Power(kilowatts)'))
##hist(hpc$Global_active_power, col = 'red', main = 'Global Active Power', xlab = 'Global Active Power(kilowatts)', ylab = 'Frequency')
dev.off()
##hpc2$Date <- strptime(paste(hpc$Date, hpc$Time), "%d/%m/%Y %H:%M:%S")
##with(hpc2, plot(Date, Global_active_power, type='l'))
## format(as.Date(hpc$Date, format = "%d/%m/%Y"), "%a")