library(dplyr)
library(grDevices)  
setwd('D:/Data Science/4. Exploratory Data Analysis/Project 1')
house_pwr_cons <- read.table(file = "hpc.txt", header = TRUE, sep = ';', na.strings = '?')
hpc_TFS <- filter(house_pwr_cons, as.Date(Date, format="%d/%m/%Y") == '2007-02-01' | as.Date(Date, format="%d/%m/%Y") == '2007-02-02')
hpc_TFS$Date <- strptime(paste(hpc_TFS$Date, hpc_TFS$Time), "%d/%m/%Y %H:%M:%S")
png(file = "plot3.png", height = 480, width = 480, units = "px")
with(hpc_TFS, plot(Date, Sub_metering_1, type='l', col='black', xlab='', ylab='Energy sub Metering'))
with(hpc_TFS, lines(Date, Sub_metering_2, col='red'))
with(hpc_TFS, lines(Date, Sub_metering_3, col='blue'))
legend("topright", pch = '-', lwd = 0, col = c('black', 'red', 'blue'), legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'))
dev.off()