##library(dplyr)
##library(grDevices)  
##setwd('D:/Data Science/4. Exploratory Data Analysis/Project 1')
##house_pwr_cons <- read.table(file = "hpc.txt", header = TRUE, sep = ';', na.strings = '?')
##hpc_TFS <- filter(house_pwr_cons, as.Date(Date, format="%d/%m/%Y") == '2007-02-01' | as.Date(Date, format="%d/%m/%Y") == '2007-02-02')
##hpc_TFS$Date <- strptime(paste(hpc_TFS$Date, hpc_TFS$Time), "%d/%m/%Y %H:%M:%S")
png(file = "plot4.png", height = 480, width = 480, units = "px")
par(mfrow = c(2,2))
with(hpc_TFS, {
    plot(Date, Global_active_power, type='l', xlab = '', ylab = 'Global Active Power(kilowatts)')
    plot(Date, Voltage, type = 'l', xlab = 'datetime', ylab = 'Voltage')  
    plot(Date, Sub_metering_1, type='l', col='black', xlab='', ylab='Energy sub Metering')
    lines(Date, Sub_metering_2, col='red')
    lines(Date, Sub_metering_3, col='blue')
    legend("topright", inset = 0.02, pch = '-', lwd = 0, cex = 1, box.lty = 0, col = c('black', 'red', 'blue'), legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'))
    plot(Date, Global_reactive_power, type = 'l', xlab = 'datetime', ylab = 'Global_reactive_power')
}
)
dev.off()
